name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # baixar o código do repositório
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Log in to Docker Web
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest

      - name: Push docker image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest

      - name: Set up Google cloud sdk
        uses: google-github-actions/setup-gcloud@0.2.0
        with:
          service_account_key: ${{ secrets.GKE_CREDENTIALS }}
          project_id: <PROJECT_ID>

      - name: Deploy to GKE
        run: |
          gcloud container clusters get_credentials <CLUSTER_NAME> --zone <ZONE>
          kubectl apply -f kubernetes/deployment.yml
