apiVersion: apps/v1
kind: Deployment
metadata:
  name: dr4at
spec:
  selector:
    matchLabels:
      app: dr4at
  replicas: 1
  template:
    metadata:
      labels:
        app: dr4at
    spec:
      containers:
        - name: dr4at
          image: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dr4at
spec:
  type: LoadBalance
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: dr4at


